### PROJECT_SETTING
project_name: "Ubuntu-1"
region: "us-east-1"

### EC2_GROUP(Security Group)
ec2_group_name: "{{ project_name }}"
vpc_id: "vpc-883c05ec"

### EC2_KEY
key_owner: "ec2_master"
pri_key_path: "~/.ssh/keys/personal/{{ key_owner }}"
pub_key_path: "~/.ssh/keys/personal/{{ key_owner }}.pub"

### EC2
ec2_instance_type: "t2.micro"
ec2_instance_tags: "{{ project_name }}"
ubuntu_server_1404: "ami-fce3c696"
security_group: "{{ ec2_group_name }}"
vpc_subnet_id: "subnet-714b2c07"
