---
- name: Playbook for application installation
  hosts: ubuntu-1
  remote_user: ubuntu
  become: true
  become_method: sudo
  vars_files:
      - vars/main.yml
  roles:
      - common
      - docker
      #- java7
      #- java8
