---
- name: Allocate new IP Address
  ec2_eip:
    region: "{{ region }}"
    device_id: "{{ ec2.instance_ids[0] }}"
  register: ec2_eip

- name: output the IP
  debug: msg="Allocated IP is {{ ec2_eip.public_ip }}"
