---
- name: Check if EC2 instance exists
  ec2_remote_facts:
    filters:
      "tag:Name": "{{ ec2_instance_tags }}"
  register: ec2_remote_facts

- name: Debug ec2_remote_facts
  debug: msg="{{ ec2_remote_facts }}"
