---
- name: Get the Administrator password
  ec2_win_password:
    region: "{{ region }}"
    instance_id: "{{ ec2.tagged_instances[0].id }}"
    key_file: "{{ pri_key_path }}"
    wait: yes
    wait_timeout: 500
  register: ec2_win_password

- name: Debug ec2_win_password
  debug: msg="{{ ec2_win_password }}"
